# Generated by Django 6.0.5 on 2026-08-22 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddestination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelsegment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_segments', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripcollaborator',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborating_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripshare',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripshare',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='destination.city'),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='travelsegment',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_segments', to='trips.tripstop'),
        ),
        migrations.AddField(
            model_name='travelsegment',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_segments', to='trips.tripstop'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='trip_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_activities', to='trips.tripstop'),
        ),
        migrations.AddField(
            model_name='expense',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.tripstop'),
        ),
        migrations.AddField(
            model_name='tripview',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='saveddestination',
            constraint=models.UniqueConstraint(fields=('user', 'city'), name='unique_saved_destination'),
        ),
        migrations.AddConstraint(
            model_name='tripcollaborator',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'order'), name='unique_stop_order_per_trip'),
        ),
    ]
